# Generated by Django 5.2.6 on 2025-09-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credits',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
