# Generated by Django 5.2.6 on 2025-09-10 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_credits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.PositiveIntegerField()),
                ('amount_paise', models.PositiveIntegerField()),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('razorpay_order_id', models.CharField(max_length=64, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=64, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('failed', 'Failed')], default='created', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'status'], name='accounts_pa_user_id_618f05_idx'), models.Index(fields=['razorpay_order_id'], name='accounts_pa_razorpa_69f12f_idx')],
            },
        ),
    ]
