# Generated by Django 5.2.6 on 2025-09-10 05:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='label',
            index=models.Index(fields=['user', 'name'], name='labels_labe_user_id_051c27_idx'),
        ),
        migrations.AddIndex(
            model_name='label',
            index=models.Index(fields=['user', 'sku_type'], name='labels_labe_user_id_5c1cf5_idx'),
        ),
        migrations.AddIndex(
            model_name='label',
            index=models.Index(fields=['user', 'category'], name='labels_labe_user_id_1e0314_idx'),
        ),
    ]
